# Generated by Django 5.2 on 2025-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_additionalmeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordering_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
