# Generated by Django 5.2 on 2025-05-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_placeorder_order"),
        ("api", "0005_remove_advertisement_link_advertisement_description_and_more"),
    ]

    operations = []
