# Generated by Django 5.2 on 2025-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_deliverylocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="eta_minutes",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                ],
                default="preparing",
                max_length=20,
            ),
        ),
    ]
