# Generated by Django 5.2 on 2025-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_order_eta_minutes_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
