# Generated by Django 5.2 on 2025-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_meal_image_url_meal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='price',
            new_name='full_price',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.AddField(
            model_name='meal',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='half_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals/'),
        ),
    ]
