# Generated by Django 5.2 on 2025-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_rename_price_meal_full_price_remove_meal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('main', 'Main Meal'), ('additional', 'Additional Meal')], default='main', max_length=20),
        ),
    ]
